<?php

namespace App\Http\Controllers;

/**
 * ╔══════════════════════════════════════════════════════════════╗
 * ║  CONTROLLER: CategoryController                              ║
 * ║  Purpose: Manage task categories                             ║
 * ║  Learning: Simple CRUD, slug generation, relationship counts ║
 * ╚══════════════════════════════════════════════════════════════╝
 */

use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of categories.
     * Route: GET /categories
     */
    public function index()
    {
        // Cache categories with task counts for 10 minutes
        $categories = Cache::remember('categories_with_counts', 600, function () {
            return Category::withCount('tasks')
                           ->orderBy('name')
                           ->get();
        });

        return view('categories.index', compact('categories'));
    }

    /**
     * Store a newly created category.
     * Route: POST /categories
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name'        => ['required', 'string', 'max:255', 'unique:categories'],
            'color'       => ['required', 'string', 'max:7', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'description' => ['nullable', 'string', 'max:500'],
        ]);

        // Slug is auto-generated by the Category model's boot() method
        Category::create($validated);

        // Clear cache so the new category appears
        Cache::forget('all_categories');
        Cache::forget('categories_with_counts');

        return redirect()->route('categories.index')
                         ->with('success', 'Category created successfully!');
    }

    /**
     * Update the specified category.
     * Route: PUT /categories/{category}
     */
    public function update(Request $request, Category $category)
    {
        $validated = $request->validate([
            'name'        => ['required', 'string', 'max:255', 'unique:categories,name,' . $category->id],
            'color'       => ['required', 'string', 'max:7', 'regex:/^#[0-9A-Fa-f]{6}$/'],
            'description' => ['nullable', 'string', 'max:500'],
        ]);

        $validated['slug'] = Str::slug($validated['name']);

        $category->update($validated);

        Cache::forget('all_categories');
        Cache::forget('categories_with_counts');

        return redirect()->route('categories.index')
                         ->with('success', 'Category updated successfully!');
    }

    /**
     * Remove the specified category.
     * Route: DELETE /categories/{category}
     */
    public function destroy(Category $category)
    {
        $category->delete();

        Cache::forget('all_categories');
        Cache::forget('categories_with_counts');

        return redirect()->route('categories.index')
                         ->with('success', 'Category deleted successfully!');
    }
}
